name: path_provider_riverpod
description: "Riverpod Provider for path_provider"
version: 1.1.0
repository: https://github.com/eaglesakura/path_provider_riverpod/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
